<?php

/**
 * @file
 * This is the main module file for Database Info Module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function solwise_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'solwise_page.admin_settings':
      return t('This Module is used for webform which have an address field, It will create an extra field above webform address field section.<\n>
        this is autocomplete field where user type postal code of UK,CA,US which returns address.<br><\n> This module Implements Loqate api to get the address
        by postal code.');
  }
}

/**
 * Implements hook_theme().
 */
function solwise_page_theme($existing, $type, $theme, $path) {
  return [
    'solwise_index_page' => [
      'variables' => [
        'pages' => null
      ],
    ],
    'solwise_index_page_2' => [
      'variables' => [
        'pages' => null
      ],
    ],
    'solwise_index_page_3' => [
      'variables' => [
        'pages' => null
      ],
    ],
    'solwise_index_page_4' => [
      'variables' => [
        'pages' => null
      ],
    ],
    'solwise_index_page_6' => [
      'variables' => [
        'pages' => null
      ],
    ],
    'solwise_product_page' => [
      'variables' => [
        'pages' => null
      ],
    ],
  ];
}

function solwise_page_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'solwise_page/solwise_page.main';
}
